name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TMDB_API: ${{ secrets.OMDB_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo environment variable (for testing only)
        run: |
          echo "OMDB_KEY is set (GitHub will mask the actual value)"
          echo "Using OMDB_KEY=$OMDB_KEY"

      - name: Use OMDB_KEY in a request
        run: |
          curl -H "Authorization: Bearer $OMDB_KEY" https://httpbin.org/bearer
